Repository spinnaker/governance, pull requests merged in 2019-09, with the labels that each got.

#31 docs(toc): Appointment of robzienert to TOC chair
  committee-technical-oversight/README.md
Labels: committee/technical-oversight, ready-for-vote

#22 Proposed updates to governance policy from SC meeting
  governance.md
Labels: committee/steering, committee/technical-oversight, ready-for-vote

#35 Slight addition to duties & member of TOC
  governance.md
Labels: committee/steering

#40 feat(docs): Adding RFC template
  rfc/.template.md
Labels: committee/technical-oversight
